# STAGE 1:
FROM node:18.6-alpine AS BUILD

WORKDIR /app

COPY ./package*.json /app
COPY ./public /app/public
COPY ./src /app/src
COPY ./.eslintrc.cjs /app
COPY ./index.html /app
COPY ./vite.config.js /app

RUN npm install

ENV NODE_OPTIONS=--max-old-space-size=900

RUN npm run build


# STAGE 2:
FROM node:18.6-alpine

COPY --from=BUILD /app/dist /app

RUN npm install -g serve

EXPOSE 3000

CMD [ "serve", "-s", "/app", "-l", "3000" ]