version: "3.8"
services:
  frontend:
    container_name: proyecto-portfolio_frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true